name: craig
author: Craig Durkin
pygments: true
baseurl: /
url: http://www.highcube.org
description:
github: http://www.github.com/durkie
twitter: http://www.twitter.com/high_cube
email: craig AT highcube.org
location: 33°45'42.73"N   84°19'52.57"W
permalink: /:title
