# Site settings
title: Craig Durkin
subtitle:
email: youremailaddress@gmail.com
description: "Hi! Here's a few things I've made..."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.highcube.org" # the base hostname & protocol for your site
author: Craig Durkin
street_address: 1234 Somewhere Road
city: Atlanta
state: GA
zip_code:
country: United States of America
phone:
permalink: /:title

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 20

# Social settings
github_url: https://github.com/durkie
twitter_url: https://twitter.com/durkie

# Build settings
markdown: kramdown

sass:
  style: compressed
